# server.port=8080
logging.level.root[0] = info
logging.level.root[1] = debug
spring.main.banner-mode = off
spring.config.import=classpath:info/db.properties
# config the mongo database # Note host and port that is enough
spring.data.mongodb.host=${MONGO_DB_HOST}
spring.data.mongodb.port=${MONGO_DB_PORT}
spring.data.mongodb.database=${MONGO_DB_NAME}
spring.data.mongodb.username=${MONGO_DB_USERNAME}
spring.data.mongodb.password=${MONGO_DB_PASSWORD}
# if you can connect but can't access collection. You just specify your role like below
spring.data.mongodb.authentication-database=admin